### PR TITLE
Vagrant support for provisioning development VMs

### PR DESCRIPTION
**Pull request by numist**
Development is hard without a test VM, and the VMware situation was never sustainable.

### CODE REVIEW

**Comment by numist** [comment]
CC: @jaswope for review

**Comment by maybefriday** [comment]
Looks like this is missing a couple of pieces before it will work on a new system:
* `/home/vagrant/sites/tmbo/admin/.config` is missing
* `/etc/php5/fpm/pool.d/www.conf` is missing, and needs to include `pm.status_path = /fpm_status` for fpm status to work
* Existing uploads/zips/logs/config should be cleaned up on `vagrant provision` (this was probably masking the first issue)

**Comment by maybefriday** [comment]
Also it would be cool if provisioning automatically pulled down and installed the [sanitized database](https://github.com/numist/this-might-be-offensive/wiki/Using-%22live%22-data).

**Comment by numist** [comment]
On second thought, the sanitized database is huge and not as sanitized as it probably should be. A dedicated test corpus would be better.

**Comment by numist** [comment]
Ready to go!

**Comment by numist** [comment]
+@kmowery for review, too

**Comment by kmowery** [comment]
1. The README text should direct you to "https://localhost:8080/", since you get an error if you go to "localhost:8080" and your browser sends an HTTP request.
2. In `admin/vm_setup.sh`, what's the point of having both remove_if_exists and backup_if_exists? Is there a need to not "backup then replace" every config file? If so, the difference should be a flag to config_file, so you don't have repeated filenames in the remove/config pattern.
3. The comment "# XXX: Share HTTPS eventually" in Vagrantfile is out of date.
4. The mysql password really shouldn't be "shortbus", especially if you might use this vagrant setup to push to production in the future. You could generate them early in `admin/vm_setup.sh` and pull them out when needed. Up to you, though; this would pass review if you choose to leave it hardcoded.

**Comment by numist** [comment]
Thanks Keaton!

1. Fixed
2. `backup_if_exists ` is for files provided by the OS/packages (since they're useful as references), `remove_if_exists` is for all the other crap that tmbo brings.
3. Sure is!
4. I'm not sure the best way to push a password out to production in the future anyway (environment?) so I'ma leave it for now :grimacing:

**Pull request merged**
